# Metadata
baseURL = "https://ut-tewh.github.io"
languageCode = "en-us"
title = "TEWH"
theme = "navigator-hugo"
summaryLength = 10

publishDir = "docs" # Tells hugo where to put the built site
pygmentsCodeFences = true # Allows code block syntax highlighting for markdown

# Site Variables
[params]
logo = "images/logos/minimal-logo.png" # Logo in top left corner

# Site Meta Data
title = "TEWH" # Site Title
author = "Conrad Li" # Site Creator
description = "Texas World Health Engineering"
languageCode = "en-us" # Language
dateFormat = "January 2, 2006" # How to format dates
home = "Home" # Name of navigation item that targets the homepage
menufixed = false

# Footer Social Media Variables
socialMediaTitle = "Follow Us"
githubLink = "https://github.com/TEWH" # Github Link
githubIcon = "images/social_icons/GitHub-Mark-Light-32px.png" # Github Icon
# Footer Email Variables
emailTitle = "Contact Us"
emailAddress = "austin.tewh@gmail.com"

# Cookies
[params.cookies]
enable = false
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Texas World Health Engineering"
description = "Driving biomedical innovation for the developing world"
tewhLogo = "images/logos/logo.png"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title = "Creating medical devices for the developing world"
description = "Texas Engineering World Health aims to bring awareness and possible solutions to healthcare inequalities in low income areas around the developing world. Each year we challenge our members to design and manufacture devices that can improve the healthcare gap found in the developing world."

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = true
topTitle= "OUR UNTOLD STORY"
title   = "Blog."
subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable  = false
#topTitle= "DROP US A NOTE"
#title   = "Contact Us."
#subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
#address = "14/05, Stockhome <br> Victori Palace , United States"
#phone   = "(03) 9283 2617"
#fax     = "+61 3827 3590"
#facebook= "https://www.facebook.com/"
#twitter = "https://twitter.com/"
#linkedin= "https://www.linkedin.com/"
#instagram= "https://www.instagram.com/"

# Site Menus
[menu]

# Navbar Menus
[[menu.nav]]
name    = "Officers"
url     = "officers"
weight  = 4

[[menu.nav]]
name    = "Projects"
url     = "projects"
weight  = 1

[[menu.nav]]
name = "Teams"
url = "teams"
weight = 2

[[menu.nav]]
name = "Calendar"
url = "calendar"
weight = 3

[[menu.nav]]
name = "Contact"
url = "contact"
weight = 5

# TODO: Member Resources page
# [[menu.nav]]
# name    = "Members"
# url     = "members"
# weight  = 3

# TODO: Maybe do more extensive about us page later?
#[[menu.nav]]
#name    = "About" # Name of navigation item
#url     = "about" # URL suffix leading to the target page (all webpage names can be vie)
#weight  = 2 # The ordering of the navigation item  (lower means earlier ordering)

# TODO: Maybe do
#[[menu.nav]]
#name    = "Blog"
#url     = "blog"
#weight  = 5